### ISSUE TITLE
Keywords aren't allowed as entity names

### ISSUE THREAD

**Issue by lmangani** [mscgenjs/mscgenjs-core#50]
Hello & Thanks for this great library!

I'm successfully able to render simple and complex `msc` and `msgenny` markup but as soon as I try to define an option such as width in `msc`, I get the following error:
```
sc {  
width=auto; 
"ac" [linecolor="#dff09aa9", textbgcolor="#dff09aa9", arclinecolor="#dff09aa9"], 
"ab" [linecolor="#149773cc", textbgcolor="#149773cc", arclinecolor="#149773cc"];
"ac" => "ab" [label="5"]; 
}
```
```
"Keywords aren't allowed as entity names (embed them in quotes if you need them)"
```

The very same script works great in the online [editor](https://mscgen.js.org/index.html?lang=xu&style=classic&msc=msc%20%7B%20%20%0Awidth%3Dauto%3B%20%0A%22ac%22%20%5Blinecolor%3D%22%23dff09aa9%22%2C%20textbgcolor%3D%22%23dff09aa9%22%2C%20arclinecolor%3D%22%23dff09aa9%22%5D%2C%20%0A%22ab%22%20%5Blinecolor%3D%22%23149773cc%22%2C%20textbgcolor%3D%22%23149773cc%22%2C%20arclinecolor%3D%22%23149773cc%22%5D%3B%0A%22ac%22%20%3D%3E%20%22ab%22%20%5Blabel%3D%225%22%5D%3B%20%0A%7D) so I suspect there is some normalization I'm missing somewhere.  I've attempted to embed quotes and/or defining the settings in the `renderMsc` function without success. Would you have a suggestion or working example to allow width definitions properly?

Thanks!

**Comment by sverweij** [comment]
hi @lmangani the `auto` value for width is part of the _xù_ language (a strict super set of mscgen). By default mscgenjs assumes the input to be `mscgen`, though, so it'll throw - as you found out. If you tell mscgenjs the input language is `xu` it'll happily parse & render it.

I've included a sample for in a browser and a simple parser call you can run directly in node.

HTH!

```html
<html>
<head>
    <!-- 
        used the minified bundle I created to work around a webpack issue because I'm lazy
        The gist of the script on the bottom will be the same whether you
        use browser globals, requirejs or webpack though.
    -->
    <script src="https://unpkg.com/mscgenjs@2.0.0/dist/webpack-issue-5316-workaround.js"></script>
</head>
<body><span id="yohere"/></body>
<script>
    const issue50 = `msc {  
        width="auto";
        "ac" [linecolor="#dff09aa9", textbgcolor="#dff09aa9", arclinecolor="#dff09aa9"], 
        "ab" [linecolor="#149773cc", textbgcolor="#149773cc", arclinecolor="#149773cc"];
        "ac" => "ab" [label="5"]; 
    }`
    mscgen.renderMsc(issue50, {inputType: "xu", elementId: "yohere"}, (pErr, pSuccess) => console.log(pErr))
</script>
</html>
```

Simple call that parses the source and emits what it understood from the input:
```javascript
const mscgenjs = require("mscgenjs");
const issue50 = `msc {  
    width="auto";
    "ac" [linecolor="#dff09aa9", textbgcolor="#dff09aa9", arclinecolor="#dff09aa9"], 
    "ab" [linecolor="#149773cc", textbgcolor="#149773cc", arclinecolor="#149773cc"];
    "ac" => "ab" [label="5"]; 
    }`

try {
    let lResult = mscgenjs.translateMsc(
        issue50,
        { inputType: "xu", outputType: "json" }
    );
    console.log(lResult);
} catch (pError) {
    console.error(pError);
}
```

**Comment by lmangani** [comment]
@sverweij thank you so much! I indeed did not try `xu` before and it works like a charm!

Mandatory screenshot from the custom [Kibana plugin](https://github.com/lmangani/kibana_diagram) using the library:
![ezgif com-optimize 2](https://user-images.githubusercontent.com/1423657/43161063-3ac787ca-8f87-11e8-9796-39faa761f349.gif)

**Comment by sverweij** [comment]
that looks awesome @lmangani !
