### ISSUE TITLE
msc-generator support

### ISSUE THREAD

**Issue by piotrwiniarczyk-silvair** [mscgenjs/mscgenjs-core#54]
What about adding support for another MSC language -> msc-generator by Zoltan Turanyi ?
It has quite few advanced features.
https://sites.google.com/site/mscgen2393/

**Comment by sverweij** [comment]
hi @piotrwiniarczyk-silvair I'm afraid I have to disappoint you ...

Supporting a new language takes a serious time investment, even when the language is well-documented (msc-generator isn't as far as I can tell) - the same goes for the new features I see in the link above (blocky arrows (?) and pipes (?)). 

Even if I would see a benefit in supporting the language and/ or features - I don't have the time to spare for such a commitment (nor for reviewing a PR to the same effect f.t.m.).

**Comment by piotrwiniarczyk-silvair** [comment]
The language is defined here:
http://msc-generator.sourceforge.net/help/6.3/msc-gen.pdf

There is also a text editor integration mode. It is done via proprietary API. Thanks for the response.
